Algoritmo "converte_salario"

Var
horas,min,valor_hora:inteiro
fracao,result,total:real

Inicio
escreval("Digite o valor das horas: ")
leia(km)
escreval("Digite o valor dos minutos: ")
leia(consumo_gasolina)
escreval("Digite o por hora: ")
leia(valor_hora)
fracao <- min/60
result <- fracao + horas
total <- result * valor_hora * 1.7

escreval("O salário total com 70% de acrescimo é: R$",total

Fimalgoritmo